import { listen } from "@tauri-apps/api/event";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { useCallback, useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import {
  Gauge,
  Keyboard,
  LayoutDashboard,
  MousePointer2,
  Settings,
  Shuffle,
  Target,
} from "lucide-react";
import { emptyRuntime } from "../app/runtime";
import { makePetCompanionViewState, type PetCompanionViewState } from "../app/petCompanionPayload";
import { petIntentLabels } from "../core/labels";
import { makePetIntent } from "../core/pet";
import type { PetIntent, PetPlacementMode } from "../core/types";
import { formatCompactDuration, formatCount } from "../core/formatters";
import {
  demoPetPackRecords,
  sourceActionAssetsForID,
  type PetPackRecord,
} from "../resources/petPack";
import type { NativeMenuAction } from "../app/nativeMenu";
import {
  cyclePlayableSourceAction,
  loopingPetFrameIndex,
  petAnimationClockNeedsWake,
  resolveDisplaySourceAction,
  type RandomSourceActionState,
} from "../app/petCompanionLogic";
import {
  nativePerformMenuBarAction,
  nativeSetPetPanelIgnoresMouseEvents,
  nativeSetPetPanelPosition,
  nativePetPanelPointerPosition,
} from "../store/native";
import { nativeCodexSessionSnapshot } from "../store/native";
import {
  onlyActiveCodexSessions,
  reduceActiveCodexEvents,
  type CodexEventEnvelope,
  type CodexSessionSnapshot,
} from "../core/codexSessions";
import { useDocumentTheme } from "../themes";
import { usePetFrames } from "./usePetFrames";
import { CodexSessionPanel } from "./CodexSessionPanel";

interface PetCompanionRendererProps {
  state: PetCompanionViewState;
  petPacks: PetPackRecord[];
  windowMode?: boolean;
  onAction?: (action: PetCompanionAction) => void;
}

interface PetDragSession {
  pointerID: number;
  startScreenX: number;
  startScreenY: number;
  origin?: { x: number; y: number };
  scaleFactor: number;
  latestPointer?: { x: number; y: number };
  pendingPosition?: { x: number; y: number };
  frameID?: number;
  moved: boolean;
}

const fallbackPreviewURL = `${import.meta.env.BASE_URL}assets/pet-luo-xiaohei.png`;

type PetCompanionAction = "open-dashboard" | "open-pet";

const placementClass = (placement: PetPlacementMode): string => `placement-${placement}`;

const petActionToNativeMenuAction = (action: PetCompanionAction): NativeMenuAction => {
  switch (action) {
    case "open-dashboard":
      return "open-today";
    case "open-pet":
      return "open-pet";
  }
};

const PetCompanionRenderer = ({ state, petPacks, windowMode = false, onAction }: PetCompanionRendererProps) => {
  const settings = state.petSettings;
  const usesNativeHitTesting = windowMode && "__TAURI_INTERNALS__" in window;
  const [isHovering, setIsHovering] = useState(false);
  const companionRef = useRef<HTMLElement>(null);
  const hitTargetRef = useRef<HTMLButtonElement>(null);
  const petHitZoneRef = useRef<HTMLSpanElement>(null);
  const hoverPanelRef = useRef<HTMLDivElement>(null);
  const bubbleRef = useRef<HTMLElement>(null);
  const hoveringRef = useRef(false);
  const draggingRef = useRef(false);
  const dragSessionRef = useRef<PetDragSession | undefined>(undefined);
  const suppressClickRef = useRef(false);
  const clickTimerRef = useRef<number | undefined>(undefined);
  const interactionTimerRef = useRef<number | undefined>(undefined);
  const [randomState, setRandomState] = useState<RandomSourceActionState>({});
  const [manualBubble, setManualBubble] = useState<string | undefined>();
  const [localPhysicalIntent, setLocalPhysicalIntent] = useState<PetIntent | undefined>();
  const [nativeCodexSessions, setNativeCodexSessions] = useState<CodexSessionSnapshot[]>(
    onlyActiveCodexSessions(state.codexSessions),
  );
  const codexSessions = windowMode
    ? nativeCodexSessions
    : onlyActiveCodexSessions(state.codexSessions);
  const selectedPack = petPacks.find((record) => record.id === settings.selectedPackID) ?? petPacks[0];
  const effectivePetIntent = localPhysicalIntent ?? state.currentPetIntent;
  const resolvedSourceAction = resolveDisplaySourceAction(
    effectivePetIntent,
    selectedPack,
    settings,
    randomState,
  );
  const sourceAction = resolvedSourceAction.action;
  const assets = sourceActionAssetsForID(selectedPack, sourceAction?.id);
  const frames = usePetFrames(assets?.frameURLs ?? [], selectedPack?.previewURL ?? fallbackPreviewURL);
  const sourceFps = sourceAction?.fps ?? 8;
  // A state transition should not make an otherwise animated pet appear frozen.
  const effectiveFps = Math.max(6, Math.min(sourceFps, isHovering ? 12 : 10));
  // Intent ids are regenerated by activity samples even when the visible
  // action has not changed. Key only by actual animation assets so those
  // samples cannot keep resetting the pet to frame zero.
  const animationKey = `${selectedPack?.id ?? "fallback"}:${sourceAction?.id ?? "preview"}`;
  const [frameIndex, setFrameIndex] = useState(0);
  const animationStartedAtRef = useRef(performance.now());
  // Codex status is a continuous external-runtime signal, so it remains visible
  // in the transparent desktop-pet window. Manual interactions still win.
  const visibleBubble = manualBubble ?? (windowMode ? undefined : state.latestPetBubble);
  const showCodexPanel = windowMode && !manualBubble && codexSessions.length > 0;
  const hoverItems = useMemo(
    () => [
      { title: "专注", value: formatCompactDuration(state.summary.focusSeconds), Icon: Target },
      { title: "走神", value: formatCompactDuration(state.summary.distractedSeconds), Icon: Gauge },
      { title: "键盘", value: formatCount(state.todayWorkload.estimatedTypedCharacters), Icon: Keyboard },
      { title: "鼠标", value: formatCount(state.todayWorkload.pointerActionCount), Icon: MousePointer2 },
    ],
    [
      state.summary.distractedSeconds,
      state.summary.focusSeconds,
      state.todayWorkload.estimatedTypedCharacters,
      state.todayWorkload.pointerActionCount,
    ],
  );

  useEffect(() => {
    animationStartedAtRef.current = performance.now();
    setFrameIndex(0);
  }, [animationKey]);

  useEffect(() => {
    if (!windowMode || !("__TAURI_INTERNALS__" in window)) return undefined;
    let disposed = false;
    let unlisten: (() => void) | undefined;
    void nativeCodexSessionSnapshot()
      .then((sessions) => {
        if (!disposed) setNativeCodexSessions(onlyActiveCodexSessions(sessions));
      })
      .catch(() => undefined);
    void listen<CodexEventEnvelope[]>("codex-session-events", (event) => {
      if (!disposed && event.payload.length > 0) {
        setNativeCodexSessions((sessions) => reduceActiveCodexEvents(sessions, event.payload));
      }
    }).then((dispose) => {
      if (disposed) dispose();
      else unlisten = dispose;
    });
    return () => {
      disposed = true;
      unlisten?.();
    };
  }, [windowMode]);

  useEffect(() => {
    if (!manualBubble) return undefined;
    const timer = window.setTimeout(() => setManualBubble(undefined), 2400);
    return () => window.clearTimeout(timer);
  }, [manualBubble]);

  const setPhysicalIntentImmediately = useCallback((kind: PetIntent["kind"], visibleMs: number) => {
    if (interactionTimerRef.current !== undefined) window.clearTimeout(interactionTimerRef.current);
    setLocalPhysicalIntent(makePetIntent(kind, "physicalInteraction", { interruptible: false }));
    if (visibleMs <= 0) {
      interactionTimerRef.current = undefined;
      return;
    }
    interactionTimerRef.current = window.setTimeout(() => {
      interactionTimerRef.current = undefined;
      setLocalPhysicalIntent(undefined);
    }, visibleMs);
  }, []);

  useEffect(() => () => {
    if (interactionTimerRef.current !== undefined) window.clearTimeout(interactionTimerRef.current);
  }, []);

  useEffect(() => {
    if (
      localPhysicalIntent &&
      state.currentPetIntent.source === "physicalInteraction" &&
      state.currentPetIntent.kind === localPhysicalIntent.kind
    ) {
      if (interactionTimerRef.current !== undefined) window.clearTimeout(interactionTimerRef.current);
      interactionTimerRef.current = undefined;
      setLocalPhysicalIntent(undefined);
    }
  }, [localPhysicalIntent, state.currentPetIntent.kind, state.currentPetIntent.source]);

  useEffect(() => {
    const nextState = resolvedSourceAction.randomState;
    if (
      randomState.packID === nextState.packID &&
      randomState.sourceActionID === nextState.sourceActionID &&
      randomState.switchedAt === nextState.switchedAt
    ) {
      return;
    }
    setRandomState(nextState);
  }, [
    randomState.packID,
    randomState.sourceActionID,
    randomState.switchedAt,
    resolvedSourceAction.randomState,
  ]);

  useEffect(() => {
    if (!settings.randomActionSwitchEnabled || !selectedPack || effectivePetIntent.source === "physicalInteraction") return undefined;
    const delay = Math.max(15, settings.randomActionSwitchSeconds) * 1000;
    const timer = window.setInterval(() => {
      setRandomState((state) => ({ ...state, switchedAt: state.switchedAt === undefined ? undefined : 0 }));
    }, delay);
    return () => window.clearInterval(timer);
  }, [
    effectivePetIntent.source,
    selectedPack,
    settings.randomActionSwitchEnabled,
    settings.randomActionSwitchSeconds,
  ]);

  useEffect(() => {
    if (frames.length <= 1) {
      setFrameIndex(0);
      return undefined;
    }
    const startedAt = animationStartedAtRef.current;
    let disposed = false;
    let frameID: number | undefined;
    let wakeCheckTimer: number | undefined;
    let unlistenNativeWake: (() => void) | undefined;
    let lastFrameAt = performance.now();
    let lastRenderedIndex = -1;
    const updateRenderedFrame = (now: number) => {
      const nextIndex = loopingPetFrameIndex(now - startedAt, frames.length, effectiveFps);
      if (nextIndex === lastRenderedIndex) return;
      lastRenderedIndex = nextIndex;
      setFrameIndex(nextIndex);
    };
    const renderFrame = (now: number) => {
      if (disposed) return;
      // Derive the phase from monotonic elapsed time. If the WebView coalesces
      // callbacks while unfocused, the next callback catches up instead of
      // leaving the companion parked on the last delivered frame.
      lastFrameAt = now;
      updateRenderedFrame(now);
      frameID = window.requestAnimationFrame(renderFrame);
    };
    const wakeIfStale = () => {
      const now = performance.now();
      if (!petAnimationClockNeedsWake(now, lastFrameAt)) return;
      if (frameID !== undefined) window.cancelAnimationFrame(frameID);
      frameID = window.requestAnimationFrame(renderFrame);
    };
    const handleWakeSignal = () => {
      const now = performance.now();
      const wasStale = petAnimationClockNeedsWake(now, lastFrameAt);
      // Tauri lifecycle events execute even when WebKit has paused rAF for an
      // inactive Space. Advance a frame synchronously so returning to a Space
      // can never reveal the exact frame that was left there.
      updateRenderedFrame(now);
      if (wasStale) {
        lastFrameAt = now;
        if (frameID !== undefined) window.cancelAnimationFrame(frameID);
        frameID = window.requestAnimationFrame(renderFrame);
      }
      if (wakeCheckTimer !== undefined) window.clearTimeout(wakeCheckTimer);
      // A Space recovery can arrive before the 750 ms boundary. Recheck once
      // the boundary has passed; a healthy chain updates lastFrameAt and makes
      // this a no-op, while a suspended WebView gets one replacement callback.
      wakeCheckTimer = window.setTimeout(wakeIfStale, 750);
    };

    frameID = window.requestAnimationFrame(renderFrame);
    document.addEventListener("visibilitychange", handleWakeSignal);
    window.addEventListener("pageshow", handleWakeSignal);
    window.addEventListener("focus", handleWakeSignal);
    if (windowMode && "__TAURI_INTERNALS__" in window) {
      void listen("focus-pet-companion-wake", handleWakeSignal).then((unlisten) => {
        if (disposed) unlisten();
        else unlistenNativeWake = unlisten;
      });
    }

    return () => {
      disposed = true;
      if (frameID !== undefined) window.cancelAnimationFrame(frameID);
      if (wakeCheckTimer !== undefined) window.clearTimeout(wakeCheckTimer);
      unlistenNativeWake?.();
      document.removeEventListener("visibilitychange", handleWakeSignal);
      window.removeEventListener("pageshow", handleWakeSignal);
      window.removeEventListener("focus", handleWakeSignal);
    };
  }, [animationKey, effectiveFps, frames.length, windowMode]);

  useEffect(() => {
    if (!settings.audioEnabled || !assets?.audioURL) return;
    const audio = new Audio(assets.audioURL);
    audio.volume = Math.min(1, Math.max(0, sourceAction?.audio?.volume ?? 0.55));
    void audio.play().catch(() => undefined);
  }, [animationKey, assets?.audioURL, settings.audioEnabled, sourceAction?.audio?.volume]);

  const updateHovering = useCallback((value: boolean) => {
    if (hoveringRef.current === value) return;
    hoveringRef.current = value;
    setIsHovering(value);
  }, []);

  const movePetWindow = useCallback((pointerID: number, screenX: number, screenY: number) => {
    const session = dragSessionRef.current;
    if (!session || session.pointerID !== pointerID) return;
    session.latestPointer = { x: screenX, y: screenY };
    if (!session.origin) return;
    const dx = (screenX - session.startScreenX) * session.scaleFactor;
    const dy = (screenY - session.startScreenY) * session.scaleFactor;
    if (!session.moved && Math.hypot(dx, dy) < 1.5 * session.scaleFactor) return;
    if (!session.moved) {
      session.moved = true;
      draggingRef.current = true;
      suppressClickRef.current = true;
      // Drag duration is user-controlled. Keep the dragged action looping
      // until pointer-up instead of expiring mid-drag after a fixed timeout.
      setPhysicalIntentImmediately("dragged", 0);
      updateHovering(false);
      void getCurrentWindow().emitTo("main", "focus-pet-companion-moved", {
        x: session.origin.x,
        y: session.origin.y,
        phase: "dragging",
      });
    }
    const unclampedX = session.origin.x + dx;
    const unclampedY = session.origin.y + dy;
    session.pendingPosition = {
      // The native command selects the monitor under the requested origin and
      // clamps the complete panel to that monitor's work area. Keeping a
      // monitor-local bound here would trap a drag on the display where it
      // started and make cross-screen dragging appear to jump back.
      x: unclampedX,
      y: unclampedY,
    };
    if (session.frameID !== undefined) return;
    session.frameID = window.requestAnimationFrame(() => {
      session.frameID = undefined;
      const position = session.pendingPosition;
      session.pendingPosition = undefined;
      if (position) void nativeSetPetPanelPosition(position.x, position.y).catch(() => undefined);
    });
  }, [setPhysicalIntentImmediately, updateHovering]);

  const finishPetDrag = useCallback(async (pointerID: number) => {
    const session = dragSessionRef.current;
    if (!session || session.pointerID !== pointerID) return;
    dragSessionRef.current = undefined;
    if (session.frameID !== undefined) window.cancelAnimationFrame(session.frameID);
    const currentWindow = getCurrentWindow();
    if (session.pendingPosition) {
      await nativeSetPetPanelPosition(session.pendingPosition.x, session.pendingPosition.y).catch(() => undefined);
    }
    if (session.moved) {
      setPhysicalIntentImmediately("landing", 1_800);
      const position = await currentWindow.outerPosition().catch(() => session.pendingPosition ?? session.origin);
      if (position) {
        await currentWindow.emitTo("main", "focus-pet-companion-moved", {
          x: position.x,
          y: position.y,
          phase: "landing",
        }).catch(() => undefined);
      }
    }
    draggingRef.current = false;
    window.setTimeout(() => {
      suppressClickRef.current = false;
    }, 0);
  }, [setPhysicalIntentImmediately]);

  useEffect(() => {
    if (!windowMode) return undefined;
    const finishActiveDrag = () => {
      const session = dragSessionRef.current;
      if (session) void finishPetDrag(session.pointerID);
    };
    const finishWhenHidden = () => {
      if (document.visibilityState !== "visible") finishActiveDrag();
    };
    // Pointer capture may be torn down by a Space change, display
    // reconfiguration, or WebView lifecycle transition without delivering the
    // button's pointerup handler. Every such exit must release native tracking.
    window.addEventListener("pointerup", finishActiveDrag, true);
    window.addEventListener("pointercancel", finishActiveDrag, true);
    window.addEventListener("blur", finishActiveDrag);
    document.addEventListener("visibilitychange", finishWhenHidden);
    return () => {
      finishActiveDrag();
      window.removeEventListener("pointerup", finishActiveDrag, true);
      window.removeEventListener("pointercancel", finishActiveDrag, true);
      window.removeEventListener("blur", finishActiveDrag);
      document.removeEventListener("visibilitychange", finishWhenHidden);
    };
  }, [finishPetDrag, windowMode]);

  useEffect(() => {
    if (!windowMode || !("__TAURI_INTERNALS__" in window)) return undefined;
    let disposed = false;
    let pending = false;
    let ignored: boolean | undefined;
    let lastDirectCaptureAt = 0;

    const contains = (rect: DOMRect, x: number, y: number): boolean =>
      x >= rect.left && x <= rect.right && y >= rect.top && y <= rect.bottom;
    const applyCapture = async (capture: boolean) => {
      if (ignored === !capture) return;
      ignored = !capture;
      await nativeSetPetPanelIgnoresMouseEvents(!capture).catch(() => undefined);
    };
    const refresh = async () => {
      if (disposed || pending) return;
      pending = true;
      try {
        const cursor = await nativePetPanelPointerPosition();
        if (!cursor) return;
        const { x, y } = cursor;
        const hitRect = petHitZoneRef.current?.getBoundingClientRect();
        const panelRect = hoverPanelRef.current?.getBoundingClientRect();
        const bubbleRect = bubbleRef.current?.getBoundingClientRect();
        const overPet = Boolean(hitRect && contains(hitRect, x, y));
        const overPanel = Boolean(hoveringRef.current && panelRect && contains(panelRect, x, y));
        const overBubble = Boolean(bubbleRect && contains(bubbleRect, x, y));
        const focusWithin = Boolean(companionRef.current?.contains(document.activeElement));
        const hoverFocusWithin = Boolean(
          hitTargetRef.current?.contains(document.activeElement)
          || hoverPanelRef.current?.contains(document.activeElement),
        );
        const directCapture = overPet || overPanel || overBubble || focusWithin;
        const now = performance.now();
        if (directCapture) lastDirectCaptureAt = now;
        const hoverGrace = hoveringRef.current && now - lastDirectCaptureAt < 90;
        const capture = draggingRef.current || directCapture || hoverGrace;
        if (overPet || overPanel || hoverFocusWithin) updateHovering(true);
        else if (!hoverGrace && !draggingRef.current) updateHovering(false);
        await applyCapture(capture);
      } finally {
        pending = false;
      }
    };

    // Cursor reads cross the WebView/native boundary. 12.5Hz remains responsive
    // while leaving substantially more main-thread time for sprite animation.
    const interval = window.setInterval(() => void refresh(), 80);
    return () => {
      disposed = true;
      window.clearInterval(interval);
      void nativeSetPetPanelIgnoresMouseEvents(false).catch(() => undefined);
    };
  }, [updateHovering, windowMode]);

  if (settings.hidden && !windowMode) return null;
  const currentFrame = frames[Math.min(frameIndex, frames.length - 1)] ?? fallbackPreviewURL;
  const cycleAction = () => {
    const next = cyclePlayableSourceAction(selectedPack, sourceAction?.id);
    if (!next.action) return;
    setRandomState(next.randomState);
    setFrameIndex(0);
    setManualBubble(`已换 ${next.action.title}`);
  };
  return (
    <aside
      ref={companionRef}
      className={`pet-companion ${windowMode ? "window-pet" : ""} ${placementClass(settings.placement)} ${isHovering ? "is-hovering" : ""} ${showCodexPanel ? "has-codex-panel" : ""}`}
      style={{ "--pet-size": `${settings.size}px`, "--pet-opacity": settings.opacity } as React.CSSProperties}
      aria-label="桌宠"
      onBlurCapture={(event) => {
        if (!windowMode && !event.currentTarget.contains(event.relatedTarget as Node | null)) updateHovering(false);
      }}
      onFocusCapture={() => updateHovering(true)}
      onPointerEnter={usesNativeHitTesting ? undefined : () => updateHovering(true)}
      onPointerLeave={usesNativeHitTesting ? undefined : () => updateHovering(false)}
    >
      {showCodexPanel ? (
        <div ref={(node) => { bubbleRef.current = node; }} className="floating-pet-codex">
          <CodexSessionPanel sessions={codexSessions} />
        </div>
      ) : visibleBubble ? <span ref={(node) => { bubbleRef.current = node; }} className="floating-pet-bubble">{visibleBubble}</span> : null}
      <button
        ref={hitTargetRef}
        className="pet-avatar-button"
        type="button"
        title={`${petIntentLabels[effectivePetIntent.kind]} · 拖动桌宠`}
        onClick={(event) => {
          if (!windowMode) return;
          if (suppressClickRef.current) {
            event.preventDefault();
            return;
          }
          if (event.detail > 1) {
            if (clickTimerRef.current !== undefined) window.clearTimeout(clickTimerRef.current);
            onAction?.("open-dashboard");
            return;
          }
          clickTimerRef.current = window.setTimeout(() => {
            setManualBubble(`${petIntentLabels[effectivePetIntent.kind]} · 专注 ${formatCompactDuration(state.summary.focusSeconds)}`);
          }, 220);
        }}
        onPointerDown={(event) => {
          if (!windowMode || !("__TAURI_INTERNALS__" in window) || event.button !== 0) return;
          const currentWindow = getCurrentWindow();
          dragSessionRef.current = {
            pointerID: event.pointerId,
            startScreenX: event.screenX,
            startScreenY: event.screenY,
            scaleFactor: 1,
            moved: false,
          };
          setPhysicalIntentImmediately("mouseSummon", 750);
          updateHovering(true);
          void nativeSetPetPanelIgnoresMouseEvents(false).catch(() => undefined);
          void Promise.all([
            currentWindow.outerPosition(),
            currentWindow.scaleFactor(),
          ]).then(([origin, factor]) => {
            const session = dragSessionRef.current;
            if (!session || session.pointerID !== event.pointerId) return;
            session.origin = origin;
            session.scaleFactor = factor;
            if (session.latestPointer) movePetWindow(session.pointerID, session.latestPointer.x, session.latestPointer.y);
          }).catch(() => undefined);
          event.currentTarget.setPointerCapture(event.pointerId);
        }}
        onPointerMove={(event: ReactPointerEvent<HTMLButtonElement>) => {
          movePetWindow(event.pointerId, event.screenX, event.screenY);
        }}
        onPointerUp={(event) => {
          void finishPetDrag(event.pointerId);
          if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId);
        }}
        onPointerCancel={(event) => {
          void finishPetDrag(event.pointerId);
        }}
        onLostPointerCapture={(event) => {
          void finishPetDrag(event.pointerId);
        }}
      >
        <span ref={petHitZoneRef} className="pet-avatar-hit-zone" aria-hidden />
        <img src={currentFrame} alt="" draggable={false} />
      </button>
      {settings.hoverStatusEnabled ? (
        <div
          ref={hoverPanelRef}
          className="pet-hover-panel"
          role="group"
          aria-label="桌宠快捷操作"
          aria-hidden={!isHovering}
          onPointerEnter={() => updateHovering(true)}
        >
          <div className="pet-hover-heading">
            <span aria-hidden />
            <div>
              <small>当前状态</small>
              <strong>{petIntentLabels[effectivePetIntent.kind]}</strong>
            </div>
          </div>
          <div className="pet-hover-metrics">
            {hoverItems.map(({ title, value, Icon }) => (
              <span key={title} title={`${title} ${value}`} aria-label={`${title} ${value}`}>
                <Icon size={17} strokeWidth={2.2} aria-hidden />
                <span>
                  <small>{title}</small>
                  <em>{value}</em>
                </span>
              </span>
            ))}
          </div>
          <div className="pet-hover-actions">
            <button type="button" title="打开面板" aria-label="打开桌宠面板" onClick={() => onAction?.("open-dashboard")}><LayoutDashboard size={16} /><span>面板</span></button>
            <button type="button" title="切换动作" aria-label="桌宠切换动作" onClick={cycleAction}><Shuffle size={17} /><span>动作</span></button>
            <button type="button" title="桌宠设置" aria-label="打开桌宠设置" onClick={() => onAction?.("open-pet")}><Settings size={16} /><span>设置</span></button>
          </div>
        </div>
      ) : null}
    </aside>
  );
};

const fallbackState = (): PetCompanionViewState => {
  const petPacks = demoPetPackRecords();
  const bundle = emptyRuntime();
  const selectedPackID = petPacks[0]?.id ?? "";
  return makePetCompanionViewState(
    {
      ...bundle.state,
      settings: {
        ...bundle.state.settings,
        pet: {
          ...bundle.state.settings.pet,
          selectedPackID,
          hidden: false,
          audioEnabled: false,
        },
      },
    },
  );
};

export const PetCompanionWindow = () => {
  const [state, setState] = useState<PetCompanionViewState>(() => fallbackState());
  useDocumentTheme(state.theme);
  const [petPacks, setPetPacks] = useState<PetPackRecord[]>(() => demoPetPackRecords());
  const emitAction = async (action: PetCompanionAction) => {
    if (!("__TAURI_INTERNALS__" in window)) return;
    await nativePerformMenuBarAction(petActionToNativeMenuAction(action));
  };

  useEffect(() => {
    if (!("__TAURI_INTERNALS__" in window)) return undefined;
    let disposed = false;
    let unlistenState: (() => void) | undefined;
    let unlistenPacks: (() => void) | undefined;
    void Promise.all([
      listen<PetCompanionViewState>("focus-pet-companion-state", (event) => setState(event.payload)),
      listen<PetPackRecord[]>("focus-pet-companion-packs", (event) => setPetPacks(event.payload)),
    ]).then(async ([disposeState, disposePacks]) => {
      if (disposed) {
        disposeState();
        disposePacks();
        return;
      }
      unlistenState = disposeState;
      unlistenPacks = disposePacks;
      await getCurrentWindow().emitTo("main", "focus-pet-companion-ready", {});
    });
    return () => {
      disposed = true;
      unlistenState?.();
      unlistenPacks?.();
    };
  }, []);

  return <PetCompanionRenderer state={state} petPacks={petPacks} windowMode onAction={(action) => void emitAction(action)} />;
};
